travis:
  secure:
    BINSTAR_TOKEN: kmzVDUorZmg3WBnoZvtd5YKLT9NJuiQ7H3p5AiSiadvsVfdI85Ubp0vr+biMQZvXzPRSOxL6bDRSWLb9+Prhl82FkPXOa5MnLtLd3dzNpo859mPwRa9m5HZ4Xo+SFUd2Y3cq3JZU4LkvBMXaGIfIt3rqPfi4HR0/az7J3kwx9wZEvg3lZyFgTOaB6A06Tdf8XzcQIXN5nB7wbRr+nYghittws8M/Ns/c/4pPVCEwoo47rJrtduIc2ZhUFY2MMpsqK+UkTz8YtNkAijmE+lrDgsYghClaVTqTQ9DXlhztEjlvNP+wqnniwRgG2IBpHhmoJCuW0VeAHh0xBRKM5LZfySA50mKeFDAZ7mQU8Xk8Hr318f+ndqW8HMuio5A3V1vH/+abqXHwXLDbI/nUQXvlm2KCnEYWE39wgnW3qmi9HPMGXfxm5NUTGtcuUzUJVf2ykiLisHF4s9zdxsz/1w1Vfellr9BOfTpCStaOUR/B/ZPLTMvaLdnPAhp+jT9AgH/1KqnyO/+2LvHN4Jf/1LVlqWoJtR9Mz+uxlO1Afe9UrQof0eAcKbob9zk5K4ddwYV9xOPMUF6eBi3Noo4uVAaKfpaPdUu8uEXYHe9ZgcMf3YmlLsGIk8j2YzEbgtRas655O/O0O+LAdMj8UrLy+U4aYiPnyG2cXAyVRO40EDo3vr4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
