travis:
  secure:
    BINSTAR_TOKEN: i8mXsg5BBicurXwYXRYwOwCCgkr3f2fahGKbHM1kgxaGw8POy9xPVNfKt9C8HaVnO/bZw8xKKQSCZphB7UAPZvWfkgvlLTJWB9C5Efp/TwKG5YsQzyzU9Bm3LqHW0wT6D1N4UOaspSo6RmUY/xcOxJc44wV8eA0WQIdPe7uJYbXMqua8R73+rw967btahQZDQxllPU1D0lYUTW1gNbe27v1XTdbIUdAOfVpciaxLbyiyvSavhHCVHV6J2dRa1jA+G7y4VlJiuYoENDYDZD4hG0FECfmjqjUkxl+gkE2sdzitbREYkXQvOodbtMDDlPGB6oW31hmVJwpaPvslqLqHiTkfGDv5o7bfjUlSU7Acp2tMp968JpMwiv+hV2u/IvvAWDZXYXXATmNa4jCZnp8iaSMZSrI4qoMe2+C6/x7NY+b0ByWirmD3R0j5P6tLqrPqUSk8yOF8RGtBMDU8qoLJVhLGs5MrDn4IJSCW+FHjctPPBoIz2ejwEEHeU0WAAteZ2L0PfxsQbrvUUXP2LF3o9zsmYnRLcU3rPrhHQbvIecQvR+4mMrJWxxkV9cpJwLyFWNtPCNPbk8gEXizvlyyUob7UwmpfCkrzfemI7hnTw+JqkQ9f8ofb6LHTTB3Qqr8bVppTeRDrU7flGV7c2gceGHOiSRSHWbtKXV+IXPxrln4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
